# Generated by Django 3.1 on 2020-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_placeholder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
