# Generated by Django 3.1 on 2020-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_website_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website_placeholder',
            field=models.CharField(default='website', max_length=100),
        ),
    ]
