# Generated by Django 3.1 on 2020-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200807_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='website_placeholder',
            field=models.CharField(blank=True, default='website', max_length=100, null=True),
        ),
    ]
